server:
  port: 8080

spring:
  application:
    name: SpringBoot_GraphQL

graphql:
  servlet:
    mapping: /graphql
    enabled: true
  tools:
    #扫描 resource 下 .graphql 后缀的文件
    schema-location-pattern: "/schema/*.graphqls"

